
# Generated by Django 1.10.4 on 2018-01-12 02:27


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aliases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=10240)),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_enable', models.BooleanField(default=False)),
                ('demo_dashboard_base_date', models.DateTimeField()),
                ('path_upload_stix_dir', models.CharField(default=b'', max_length=100)),
                ('path_sharing_policy_specifications', models.CharField(default=b'', max_length=100)),
                ('path_bootstrap_css_dir', models.CharField(default=b'', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GVAuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_l1_view', models.BooleanField(default=True)),
                ('is_l2_view', models.BooleanField(default=True)),
                ('is_sharing_view', models.BooleanField(default=False)),
                ('css_thema', models.CharField(default=b'default', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Taxii',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('address', models.CharField(default=b'localhost', max_length=100)),
                ('port', models.IntegerField(default=80)),
                ('ssl', models.BooleanField(default=False)),
                ('path', models.CharField(default=b'/taxii-data', max_length=100)),
                ('collection', models.CharField(default=b'Default', max_length=100)),
                ('login_id', models.CharField(default=b'login_id', max_length=100)),
                ('login_password', models.CharField(default=b'login_password', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CtirsConfig',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ctim.GVAuthUser')),
                ('ctirs_username', models.CharField(default=b'', max_length=100)),
                ('ctirs_apikey', models.CharField(default=b'', max_length=100)),
                ('ctirs_host', models.CharField(default=b'', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='gvauthuser',
            name='stip_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='config',
            name='default_taxii',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.SET_DEFAULT, to='ctim.Taxii'),
        ),
        migrations.AddField(
            model_name='aliases',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ctim.GVAuthUser'),
        ),
    ]
