# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-08 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctim', '0002_auto_20180112_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctirsconfig',
            name='ctirs_apikey',
        ),
        migrations.RemoveField(
            model_name='ctirsconfig',
            name='ctirs_username',
        ),
        migrations.AlterField(
            model_name='ctirsconfig',
            name='ctirs_host',
            field=models.CharField(default=b'https://localhost:10001', max_length=100),
        ),
    ]
