
# Generated by Django 1.10.4 on 2019-02-08 07:07


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctim', '0004_auto_20190207_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gvauthuser',
            name='stip_user',
        ),
        migrations.AlterField(
            model_name='aliases',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ctirs.GVAuthUser'),
        ),
        migrations.AlterField(
            model_name='ctirsconfig',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ctirs.GVAuthUser'),
        ),
        migrations.DeleteModel(
            name='GVAuthUser',
        ),
    ]
